# docker-compose up
# docker-compose down --rmi all -v

version: "3.8"
services:
  discord_service:
    build: ./discord
    container_name: discord-srvc
    links:
      - ai_service

  ai_service:
    build: ./ai
    container_name: ai-srvc
    ports:
      - '5000:5000'
    links:
      - faiss_service

  faiss_service:
    build: ./db
    container_name: faiss-srvc
    ports:
      - '5001:5001'