version: "3.8"
services:
  discord_bot:
    build: ./discord
    container_name: discord_bot
    links:
      - math_agent

  math_agent:
    build: ./ai
    container_name: math_agent
    ports:
      - '5000:5000'
    links:
      - vector_store

  vector_store:
    build: ./db
    container_name: vector_store
    ports:
      - '5001:5001'